\-------------------
\    	METODI
\-------------------

\ Colora tutti i pixel dello scermo di nero
: CLEAR														\ (    --    )
    HL SPIXEL  BLACK SCOLOR  300 400 PRINT_PIXEL
;

\ Crea un borso di spessore 4 intorno allo schermo
: BORDER													\ (    --    )
	HL SPIXEL  				   4   400  PRINT_PIXEL
	HL SPIXEL  				   300 4    PRINT_PIXEL
	HR SPIXEL -3 INC_PIXEL_O   300 4    PRINT_PIXEL
	LL SPIXEL -3 INC_PIXEL_V   4   400  PRINT_PIXEL 
;

\ Crea un contorno al pulsante PLAY
: SEL_PLAY													\ (    --    )
	3EAF8674 SPIXEL  2  C0 PRINT_PIXEL
	3EAF8674 SPIXEL  59 2  PRINT_PIXEL
	3EB4F67C SPIXEL  2  C0 PRINT_PIXEL
	3EAF8974 SPIXEL  59 2  PRINT_PIXEL
;

\ Crea un contorno al pulsante EXIT
: SEL_EXIT													\ (    --    )
	3EB62674 SPIXEL  2  C0 PRINT_PIXEL
	3EB62674 SPIXEL  59 2  PRINT_PIXEL
	3EBB967C SPIXEL  2  C0 PRINT_PIXEL
	3EB62974 SPIXEL  59 2  PRINT_PIXEL
;


\ Stampa pulsanti PLAY ed EXIT
: PRINT_BUTTONS												\ (    --    )
	6 SCHAR_SIZE
	3EB0C6EC SPIXEL  .P. .L. .A. .Y. 4 PRINT_WORD
	3EB766EC SPIXEL  .E. .X. .I. .T. 4 PRINT_WORD
	SEL_PLAY
;

\ Permette la selezione del pulsante PLAY o EXIT
: CONTROL_BUTTONS											\ (    --    )
	0
	BEGIN
		CONTROL_RECEIVER2  GSAMPLE
		DUP 2 =  IF
			SWAP DUP  1 =  IF
				1 - BLACK SCOLOR  SEL_EXIT
					WHITE SCOLOR  SEL_PLAY
			THEN
			SWAP
		ELSE
			DUP 8 =  IF
				SWAP DUP  0 =  IF
					1 + BLACK SCOLOR  SEL_PLAY
						WHITE SCOLOR  SEL_EXIT
				THEN
				SWAP
			THEN
		THEN
		GCLOCK STIME
		BEGIN  13880 GCLOCK GTIME - <  UNTIL
	5 = UNTIL
;

\ Inizializazione di SELECTION
: INITIALIZE_SELECTION										\ (    --    )
    CLEAR   WHITE SCOLOR   BORDER
    18 SCHAR_SIZE  3E9B6290 SPIXEL
	.S. .N. .A. .K. .E. 5 PRINT_WORD
	PRINT_BUTTONS 
;

\ Inizializzazione di PLAY								\ (    --    )
: INITIALIZE_PLAY
    CLEAR   WHITE SCOLOR   BORDER

	3E97A000 SPIXEL  4 400 PRINT_PIXEL
	
	4 SCHAR_SIZE
	3E914068 SPIXEL  .S. .C. .O. .R. .E. .DP.  6 PRINT_WORD
	3E9142A8 SPIXEL   SET_SCORE   0 PRINT_NUMBER

    3E946068 SPIXEL  .T. .I. .M. .E. .DP. 5 PRINT_WORD  
	3E946248 STIMER_PIXEL
	WHITE STIMER_COLOR   4 STIMER_SIZE   SET_TIMER

    PRINT_SNAKE  PRINT_APPLE  DROP

	0 SSTATE_RECEIVER
	BEGIN  CONTROL_RECEIVER2  GSAMPLE 5 =  UNTIL
    6 SSAMPLE
	SAVE_TIMER
;

\ Blocca il flusso di esecuzione e attende il comando
\ per ricominciare 
: PAUSE_INTERFACE											\ (    --    )
	3E9145E0 SPIXEL  WHITE SCOLOR  A SCHAR_SIZE
	.P. .A. .U. .S. .E. 5 PRINT_WORD

	BEGIN  CONTROL_RECEIVER2 GSAMPLE 5 =  UNTIL

	3E9145E0 SPIXEL  BLACK SCOLOR
	.P. .A. .U. .S. .E. 5 PRINT_WORD
	
	GHEAD_DIR
	DUP 0 =  IF 6 SSAMPLE  ELSE
	DUP 1 =  IF 8 SSAMPLE  ELSE
	DUP 2 =  IF 4 SSAMPLE  ELSE
				2 SSAMPLE
	THEN THEN THEN
    DROP
;

\ Inizializzazione di GAME_OVER
: INITIALIZE_GAME_OVER														\ (    --    )
	CLEAR  WHITE SCOLOR  BORDER

	3E973234 SPIXEL  E SCHAR_SIZE   
	.G. .A. .M. .E. .SPACE. .O. .V. .E. .R.  9 PRINT_WORD

	3EA38604 SPIXEL  4 SCHAR_SIZE   .T. .I. .M. .E. .DP.  5 PRINT_WORD
	3EA387E4 SPIXEL 

	GMINUTES  DUP A / 0 =  IF  0 PRINT_NUMBER  THEN
	PRINT_NUMBER  .DP. PRINT_CHAR  8 INC_PIXEL_O
	
	GSECONDS  DUP A / 0 =  IF  0 PRINT_NUMBER  THEN
	PRINT_NUMBER  .DP. PRINT_CHAR  8 INC_PIXEL_O

	GDECSECONDS PRINT_NUMBER

	3EA7C604 SPIXEL  .S. .C. .O. .R. .E. .DP. 6 PRINT_WORD
	3EA7C844 SPIXEL  GSCORE PRINT_NUMBER
	
	PRINT_BUTTONS
;
